language: scala
matrix:
  include:
  - jdk: oraclejdk8
  - jdk: openjdk11
    dist: xenial
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
script:
- git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
- git show --oneline --check
- sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test testConscript
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
